server:
  port: 8080

spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    druid:
      # 数据库 1
      db1:
        url: jdbc:mysql://m3880i.tjtn.db.lecloud.com:3880/medical_mall?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: shangcheng_t_new
        password: YzFlNjhlNjAzZTIMDhmZjkzYTc3Y2M
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      # 数据库 2
      db2:
        url: jdbc:mysql://m3880i.tjtn.db.lecloud.com:3880/medicine_trace?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: shangcheng_t_new
        password: YzFlNjhlNjAzZTIMDhmZjkzYTc3Y2M
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20





